services:
  database:
    image: postgres
    hostname: postgres
    container_name: reddit-db
    environment:
      POSTGRES_DB: redditdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    container_name: reddit-rabbitmq
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/mnesia

  test-database:
    image: postgres
    hostname: postgres-test
    container_name: reddit-test-db
    environment:
      POSTGRES_DB: redditdb_pytest
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    env_file:
      - .env
    ports:
      - "5434:5432"

volumes:
  pgdata:
  rabbitmq_data: